on:
  push:
    branches: [main, master]

name: "Check NetLogo Manually (Older Versions)"

permissions: read-all

jobs:
  check-netlogo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NetLogo 6.4.0
        uses: danielvartan/netlogo-actions/setup-netlogo@v1
        with:
          version: '6.4.0'

      - name: Run Experiment
        run: |
          model_dir="$NETLOGO_HOME/models/IABM Textbook/chapter 7"
          model_file="Voting Sensitivity Analysis.nlogo"
          experiment_name="sensitivity-experiment"
          table_file="/tmp/table.csv"

          netlogo \
            --headless \
            --model "$model_dir/$model_file" \
            --experiment "$experiment_name" \
            --table "$table_file"

          cat "$table_file"
