name: setup-netlogo
author: Daniel Vartanian
description: |
  This GitHub Action installs NetLogo on the runner by downloading the
  appropriate bundle, configuring environment variables, and updating the system
  PATH. It supports `ubuntu-latest`, `macos-latest`, and `windows-latest`
  runners, and only NetLogo versions 6.4.0 and above.

  Bundles are downloaded from the official NetLogo GitHub releases using
  GitHub CLI. The `GH_TOKEN` environment variable must be set in the workflow to
  authenticate GitHub API requests. This avoids rate limiting issues.
inputs:
  version:
    description: |
      A single-quoted (!important!) character string indicating the NetLogo
      version to use (e.g., `'7.0.3'`). Use `'release'` to get the latest
      stable release. Only versions 6.4.0 and above are supported.
    default: 'release'
  cache:
    description: |
      A single-quoted (!important!) boolean value indicating whether the NetLogo
      installation should be cached across runs.
    default: 'true'
runs:
  using: composite
  steps:
    - name: Validate arguments
      run: |
        # Validate arguments
        # set -x

        if [[ ! "${{inputs.version}}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]] && \
           [[ "${{inputs.version}}" != "release" ]]; then
          echo \
            "Error: Invalid version format" \
            "('${{inputs.version}}')." \
            "Use semantic versioning (e.g., '7.0.2') or use" \
            "'release' to get the latest stable release."

          exit 1
        fi

        if [[ "${{inputs.version}}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          major_version="${BASH_REMATCH[1]}"
          minor_version="${BASH_REMATCH[2]}"

          if (( major_version < 6 )) || \
             (( major_version == 6 && minor_version < 4 )) ; then
            echo \
              "Error: Unsupported NetLogo version" \
              "('${{inputs.version}}')." \
              "Only versions equal or greater than 6.4.0 are supported."

            exit 1
          fi

          if [[ "${{inputs.version}}" == "6.4.0" ]] &&
             [[ "${RUNNER_ARCH}" =~ ^(ARM|ARM64)$ ]]; then
            echo \
              "Error: NetLogo 6.4.0 and earlier versions are not" \
              "available for this architecture (${RUNNER_ARCH})."

            exit 1
          fi
        fi

        if [[ "${{inputs.cache}}" != "true" ]] && \
           [[ "${{inputs.cache}}" != "false" ]]; then
          echo \
            "Error: Invalid cache option" \
            "('${{inputs.cache}}')." \
            "Valid options are 'true' or 'false'."

          exit 1
        fi
      shell: bash

    - name: Get NetLogo version
      id: netlogo-version
      run: |
        # Get NetLogo version
        # set -x

        if [[ "${{inputs.version}}" == "release" ]]; then
          version_tag=$( \
            gh api repos/NetLogo/NetLogo/releases/latest -q .tag_name \
          )

          if [[ -z "${version_tag}" || "${version_tag}" == "null" ]]; then
            echo \
              "Error: Could not fetch latest NetLogo version from GitHub API."

            exit 1
          fi

          NETLOGO_VERSION="${version_tag#v}"
        else
          NETLOGO_VERSION="${{inputs.version}}"
        fi

        echo "version=${NETLOGO_VERSION}" >> "${GITHUB_OUTPUT}"
        echo "NETLOGO_VERSION=${NETLOGO_VERSION}" >> "${GITHUB_ENV}"
      shell: bash

    - name: Set cache path
      id: cache-path
      if: inputs.cache == 'true'
      run: |
        # Set cache path
        # set -x

        case ${RUNNER_OS} in
          "Linux")
            cache_path="/opt/NetLogo ${NETLOGO_VERSION}"
            ;;
          "macOS")
            cache_path="/Applications/NetLogo ${NETLOGO_VERSION}.app"
            ;;
          "Windows")
            case ${RUNNER_ARCH} in
              "X64")
                cache_path="C:\Program Files\NetLogo ${NETLOGO_VERSION}"
                ;;
              "X86")
                cache_path="C:\Program Files (x86)\NetLogo ${NETLOGO_VERSION}"
                ;;
            esac
            ;;
        esac

        echo "path=${cache_path}" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Restore NetLogo from cache
      id: netlogo-cache
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ steps.cache-path.outputs.path }}
        key: "netlogo-${{steps.netlogo-version.outputs.version}}-${{runner.os}}-${{runner.arch}}"

    - name: Choose correct bundle for OS type
      id: netlogo-bundle
      if: |
        inputs.cache != 'true' ||
        steps.netlogo-cache.outputs.cache-hit != 'true'
      run: |
        # Choose correct bundle for OS type
        # set -x

        case ${RUNNER_OS} in
          "Linux")
              case ${RUNNER_ARCH} in
                "X64")
                  extension="64.tgz"
                  ;;
                "X86")
                  extension="32.tgz"
                  ;;
                *)
                  echo "${RUNNER_OS} "${RUNNER_ARCH}" not supported"

                  exit 1
                  ;;
              esac
              ;;
           "macOS")
              case "${RUNNER_ARCH}" in
                "X86" | "X64")
                  extension="x86_64.dmg"
                  ;;
                *)
                  extension="aarch64.dmg"
                  ;;
              esac
              ;;
           "Windows")
              case "${RUNNER_ARCH}" in
                "X64")
                  extension="64.msi"
                  ;;
                "X86")
                  extension="32.msi"
                  ;;
                *)
                  echo "${RUNNER_OS} ${RUNNER_ARCH} not supported"

                  exit 1
                  ;;
              esac
              ;;
            *)
              echo "${RUNNER_OS} not supported"

              exit 1
              ;;
        esac

        echo "extension=${extension}" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Download NetLogo
      id: netlogo-download
      if: |
        inputs.cache != 'true' ||
        steps.netlogo-cache.outputs.cache-hit != 'true'
      run: |
        # Download NetLogo
        # set -x

        repo="NetLogo/NetLogo"
        tag="v${NETLOGO_VERSION}"
        extension="${{steps.netlogo-bundle.outputs.extension}}"

        gh release download "$tag" \
          --repo "$repo" \
          --pattern "*${extension}" \
          --clobber

        bundle=$(ls *"${extension}" | head -1)

        if [[ -z "$bundle" ]]; then
          echo \
            "Error: No file matching" \
            "'*${extension}' found in release '${tag}'."

          exit 1
        fi

        echo "bundle=${bundle}" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Set NetLogo home
      run: |
        # Set NetLogo home
        # set -x

        case ${RUNNER_OS} in
          "Linux")
              netlogo_home="/opt/NetLogo ${NETLOGO_VERSION}"
              ;;
           "macOS")
              netlogo_home="/Applications/NetLogo ${NETLOGO_VERSION}"
              ;;
           "Windows")
              case "${RUNNER_ARCH}" in
                "X64")
                  netlogo_home="/c/Program Files/NetLogo ${NETLOGO_VERSION}"
                  ;;
                "X86")
                  netlogo_home="/c/Program Files (x86)/NetLogo ${NETLOGO_VERSION}"
                  ;;
              esac
              ;;
            *)
              echo "${RUNNER_OS} not supported"

              exit 1
              ;;
        esac

        echo "NETLOGO_HOME=${netlogo_home}" >> "${GITHUB_ENV}"
      shell: bash

    - name: Install NetLogo
      if: |
        inputs.cache != 'true' ||
        steps.netlogo-cache.outputs.cache-hit != 'true'
      run: |
        # Install NetLogo
        # set -x

        bundle="${{steps.netlogo-download.outputs.bundle}}"

        case ${RUNNER_OS} in
          "Linux")
              netlogo_console_path=$( \
                tar -tzf "${bundle}" \
                  | grep "NetLogo_Console$" \
                  | head -n 1 \
              )

              if [[ -z "${netlogo_console_path}" ]]; then
                echo "Error: 'NetLogo_Console' not found in bundle."

                exit 1
              fi

              netlogo_console_dir=$(dirname "${netlogo_console_path}")

              sudo mkdir -p "${NETLOGO_HOME}"

              if [[ "${netlogo_console_dir}" == "." ]]; then
                sudo tar \
                  -xzf "${bundle}" \
                  -C "${NETLOGO_HOME}"
              else
                sudo tar \
                  -xzf "${bundle}" \
                  -C "${NETLOGO_HOME}" \
                  --strip-components=1
              fi
              ;;
           "macOS")
              netlogo_mountpoint='/tmp/netlogo_mountpoint'

              mkdir -p "${netlogo_mountpoint}"

              hdiutil attach "${bundle}" \
                -mountpoint "${netlogo_mountpoint}" \
                -quiet

              netlogo_console_path=$( \
                find "${netlogo_mountpoint}" -name "NetLogo_Console" \
                  | head -n 1 \
              )

              if [[ -z "${netlogo_console_path}" ]]; then
                echo "Error: 'NetLogo_Console' not found in bundle."

                exit 1
              fi

              netlogo_console_dir=$(dirname "${netlogo_console_path}")

              sudo mkdir -p "${NETLOGO_HOME}"
              sudo cp -Rp "${netlogo_console_dir}/." "${NETLOGO_HOME}"

              hdiutil detach "${netlogo_mountpoint}" -force -quiet
              rm -rf "${netlogo_mountpoint}"
              ;;
           "Windows")
              powershell.exe \
                -Command \
                "Start-Process msiexec.exe \
                -ArgumentList '/i \"${bundle}\" /qn /norestart \
                /l*v msi_install.log' \
                -Wait"

              netlogo_console_path="${NETLOGO_HOME}/NetLogo_Console.exe"

              if [[ ! -f "${netlogo_console_path}" ]]; then
                echo \
                  "Error: NetLogo installation failed." \
                  "Check msi_install.log."

                tail -n 100 msi_install.log

                exit 1
              fi
              ;;
            *)
              echo "${RUNNER_OS} not supported"

              exit 1
              ;;
        esac

        rm -f "${bundle}"
      shell: bash

    - name: Set environment variables
      run: |
        # Set environment variables
        # set -x

        bundle="${{steps.netlogo-download.outputs.bundle}}"

        case ${RUNNER_OS} in
          "Linux" | "macOS")
              netlogo_console="${NETLOGO_HOME}/NetLogo_Console"
              ;;
           "Windows")
              netlogo_console="${NETLOGO_HOME}\NetLogo_Console.exe"
              ;;
            *)
              echo "${RUNNER_OS} not supported"

              exit 1
              ;;
        esac

        echo "NETLOGO_CONSOLE=${netlogo_console}" >> "${GITHUB_ENV}"
        echo "${NETLOGO_HOME}" >> "${GITHUB_PATH}"
      shell: bash

    - name: Create symbolic links
      run: |
        # Create symbolic links
        # set -x

        case ${RUNNER_OS} in
          "Linux")
            netlogo_binary="${NETLOGO_HOME}/bin/NetLogo"

            sudo ln -sf "${netlogo_binary}" "/usr/local/bin/NetLogo"
            sudo ln -sf "${netlogo_binary}" "/usr/local/bin/netlogo"
            ;;
          "macOS")
            netlogo_binary="${NETLOGO_HOME}/NetLogo 7.0.3.app/Contents/MacOS/NetLogo 7.0.3"

            sudo ln -sf "${netlogo_binary}" "/usr/local/bin/NetLogo"
            sudo ln -sf "${netlogo_binary}" "/usr/local/bin/netlogo"
            ;;
          "Windows")
            symlink_target=$(cygpath -w "${NETLOGO_HOME}/NetLogo.exe")

            # On Windows, creating one link allows you to call either name
            # from the CLI.
            cmd //c mklink \
              "C:\Windows\System32\NetLogo.exe" \
              "${symlink_target}"
            ;;
        esac
      shell: bash

    - name: Test NetLogo installation
      run: |
        # Test NetLogo installation
        netlogo --headless --version
      shell: bash
