name: setup-netlogo
author: Daniel Vartanian
description: |
  This GitHub Action sets up the NetLogo environment on a Linux runner by
  downloading and installing NetLogo, configuring environment variables, and
  updating the system PATH. Only versions 6.4.0 and above are supported.
inputs:
  version:
    description: |
      A single-quoted (!important) character string indicating the NetLogo
      version to use (e.g., `'7.0.2'`). Use `'release'` to get the latest
      stable release. Only versions 6.4.0 and above are supported.
    default: 'release'
  cache:
    description: |
      A single-quoted (!important) boolean value indicating whether the NetLogo
      installation should be cached across runs.
    default: 'true'
runs:
  using: composite
  steps:
    - name: Validate arguments
      run: |
        # Validate arguments
        if [[ ! "${{inputs.version}}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]] && \
           [[ "${{inputs.version}}" != "release" ]]; then
          echo \
            "Error: Invalid version format" \
            "('${{inputs.version}}')." \
            "Use semantic versioning (e.g., '7.0.2') or use" \
            "'release' to get the latest stable release."

          exit 1
        fi

        if [[ "${{inputs.version}}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          major_version="${BASH_REMATCH[1]}"
          minor_version="${BASH_REMATCH[2]}"

          if (( major_version < 6 )) || \
             (( major_version == 6 && minor_version < 4 )) ; then
            echo \
              "Error: Unsupported NetLogo version" \
              "('${{inputs.version}}')." \
              "Only versions equal or greater than 6.4.0 are supported."

            exit 1
          fi

          if [[ "${{inputs.version}}" == "6.4.0"]] &&
             [[ "${RUNNER_ARCH}" =~ ^(ARM|ARM64)$ ]]; then
            echo \
              "Error: NetLogo 6.4.0 and earlier versions are not" \
              "available for this architecture (${RUNNER_ARCH})."

            exit 1
          fi
        fi

        if [[ "${{inputs.cache}}" != "true" ]] && \
           [[ "${{inputs.cache}}" != "false" ]]; then
          echo \
            "Error: Invalid cache option" \
            "('${{inputs.cache}}')." \
            "Valid options are 'true' or 'false'."

          exit 1
        fi
      shell: bash

    - name: Determine NetLogo version
      id: netlogo-version
      run: |
        # Determine NetLogo version
        if [[ "${{inputs.version}}" == "release" ]]; then
          NETLOGO_VERSION=$( \
            curl -s \
              https://api.github.com/repos/NetLogo/NetLogo/releases/latest \
              | grep -o '"tag_name":[[:space:]]*"v\?[0-9.]*"' \
              | grep -o '[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?' \
          )

          NETLOGO_VERSION=$( \
            curl -s \
              https://api.github.com/repos/NetLogo/NetLogo/releases/latest \
              | grep -oP '"tag_name":\s*"\Kv?[0-9]+\.[0-9]+(\.[0-9]+)?' \
              | tr -d 'v' \
          )

          if [[ -z "${NETLOGO_VERSION}" ]]; then
            echo \
              "Error: Could not fetch latest NetLogo version from GitHub API."

            exit 1
          fi
        else
          NETLOGO_VERSION="${{inputs.version}}"
        fi

        echo "version=${NETLOGO_VERSION}" >> "${GITHUB_OUTPUT}"
        echo "NETLOGO_VERSION=${NETLOGO_VERSION}" >> "${GITHUB_ENV}"
      shell: bash


    - name: Set cache path
      id: cache-path
      run: |
        # Set cache path
        case ${RUNNER_OS} in
          "Linux")
            echo "path=/opt/NetLogo-${NETLOGO_VERSION}" >> "${GITHUB_OUTPUT}"
            ;;
          "macOS")
            echo "path=/Applications/NetLogo ${NETLOGO_VERSION}.app" >> "${GITHUB_OUTPUT}"
            ;;
          "Windows")
            case ${RUNNER_ARCH} in
              X64)
                echo "path=C:\Program Files\NetLogo ${NETLOGO_VERSION}" >> "${GITHUB_OUTPUT}"
                ;;
              X86)
                echo "path=C:\Program Files (x86)\NetLogo ${NETLOGO_VERSION}" >> "${GITHUB_OUTPUT}"
                ;;
            esac
            ;;
        esac
      shell: bash

    - name: Restore NetLogo cache
      id: netlogo-cache
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ steps.cache-path.outputs.path }}
        key: "netlogo-${{steps.netlogo-version.outputs.version}}-${{runner.os}}-${{runner.arch}}"

    - name: Choose correct bundle for OS type
      id: netlogo-bundle
      if: |
        inputs.cache != 'true' ||
        steps.netlogo-cache.outputs.cache-hit != 'true'
      run: |
        # Choose correct bundle for OS type
        case ${RUNNER_OS} in
          "Linux")
              case ${RUNNER_ARCH} in
                X64)
                  echo "bundle_ext=64.tgz" >> "${GITHUB_OUTPUT}"
                  ;;
                X86)
                  echo "bundle_ext=32.tgz" >> "${GITHUB_OUTPUT}"
                  ;;
                *)
                  echo "${RUNNER_OS} ${RUNNER_ARCH} not supported"
                  exit 1
                  ;;
              esac
              ;;
           "macOS")
              case ${RUNNER_ARCH} in
                X86|X64)
                  echo "bundle_ext=x86_64.dmg" >> "${GITHUB_OUTPUT}"
                  ;;
                *)
                  echo "bundle_ext=aarch64.dmg" >> "${GITHUB_OUTPUT}"
                  ;;
              esac
              ;;
           "Windows")
              case ${RUNNER_ARCH} in
                X64)
                  echo "bundle_ext=64.msi" >> "${GITHUB_OUTPUT}"
                  ;;
                X86)
                  echo "bundle_ext=32.msi" >> "${GITHUB_OUTPUT}"
                  ;;
                *)
                  echo "${RUNNER_OS} ${RUNNER_ARCH} not supported"
                  exit 1
                  ;;
              esac
              ;;
            *)
              echo "${RUNNER_OS} not supported"
              exit 1
              ;;
        esac
      shell: bash

    - name: Download NetLogo
      id: netlogo-download
      if: |
        inputs.cache != 'true' ||
        steps.netlogo-cache.outputs.cache-hit != 'true'
      run: |
        # Download NetLogo
        release_api_url=$( \
          printf "%s%s" \
            "https://api.github.com/repos/NetLogo/NetLogo/releases/tags/" \
            "v${NETLOGO_VERSION}" \
        )

        download_url=$( \
          curl -s "${release_api_url}" \
          | grep -o '"browser_download_url":[[:space:]]*"[^"]*'"${{steps.netlogo-bundle.outputs.bundle_ext}}"'"' \
          | grep -o 'https://[^"]*' \
          | head -1 \
        )

        if [[ -z "${download_url}" ]]; then
          echo \
            "Error: Could not find download URL for NetLogo" \
            "${NETLOGO_VERSION} (${{runner.os}} ${{runner.arch}})."

          exit 1
        fi

        bundle="$(basename "${download_url}")"

        wget \
          "${download_url}" -qO "${bundle}" || \
          { echo "Error: Download failed"; exit 1; }

        echo "bundle=${bundle}" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Install NetLogo and set environment variables
      if: |
        inputs.cache != 'true' ||
        steps.netlogo-cache.outputs.cache-hit != 'true'
      run: |
        # Install NetLogo and set environment variables
        bundle="${{steps.netlogo-download.outputs.bundle}}"

        case ${RUNNER_OS} in
          "Linux")
              NETLOGO_HOME="/opt/NetLogo-${NETLOGO_VERSION}"

              netlogo_console_path=$( \
                tar -tzf "${bundle}" \
                | grep "_Console$" \
                | head -1 \
              )

              if [[ -z "${netlogo_console_path}" ]]; then
                echo "Error: NetLogo_Console not found in bundle."
                exit 1
              fi

              netlogo_console_dir=$(dirname "${netlogo_console_path}")

              sudo mkdir -p "${NETLOGO_HOME}"

              if [[ "${netlogo_console_dir}" == "." ]]; then
                sudo tar \
                  -xzf "${bundle}" \
                  -C "${NETLOGO_HOME}"
              else
                sudo tar \
                  -xzf "${bundle}" \
                  -C "${NETLOGO_HOME}" \
                  --strip-components=1
              fi

              echo "NETLOGO_HOME=${NETLOGO_HOME}" >> "${GITHUB_ENV}"
              echo "NETLOGO_CONSOLE=${NETLOGO_HOME}/NetLogo_Console" >> "${GITHUB_ENV}"
              echo "${NETLOGO_HOME}" >> "${GITHUB_PATH}"
              ;;
           "macOS")
              NETLOGO_HOME="/Applications/NetLogo ${NETLOGO_VERSION}.app"

              hdiutil attach "${bundle}"

              volume_path=$(hdiutil info | grep "/Volumes/NetLogo" | awk '{print $1}')

              sudo cp -R "/Volumes/NetLogo ${NETLOGO_VERSION}/NetLogo ${NETLOGO_VERSION}.app" \
                "${NETLOGO_HOME}"

              hdiutil detach "${volume_path}"

              echo "NETLOGO_HOME=${NETLOGO_HOME}" >> "${GITHUB_ENV}"
              echo "NETLOGO_CONSOLE=${NETLOGO_HOME}/Contents/MacOS/NetLogo_Console" >> "${GITHUB_ENV}"
              echo "${NETLOGO_HOME}/Contents/MacOS" >> "${GITHUB_PATH}"
              ;;
           "Windows")
              NETLOGO_HOME=$( \
                case ${RUNNER_ARCH} in
                  X64)
                    echo "C:\Program Files\NetLogo ${NETLOGO_VERSION}"
                    ;;
                  X86)
                    echo "C:\Program Files (x86)\NetLogo ${NETLOGO_VERSION}"
                    ;;
                esac
              )

              msiexec /i "${bundle}" /qn /norestart INSTALLDIR="${NETLOGO_HOME}"

              echo "NETLOGO_HOME=${NETLOGO_HOME}" >> "${GITHUB_ENV}"
              echo "NETLOGO_CONSOLE=${NETLOGO_HOME}\NetLogo_Console.exe" >> "${GITHUB_ENV}"
              echo "${NETLOGO_HOME}" >> "${GITHUB_PATH}"
              ;;
            *)
              echo "${RUNNER_OS} not supported"
              exit 1
              ;;
        esac

        rm -f "${bundle}"
      shell: bash


    - name: Create symbolic links
      run: |
        # Create symbolic links
        case ${RUNNER_OS} in
          "Linux")
            sudo ln -sf \
              "${NETLOGO_HOME}/bin/NetLogo" \
              /usr/local/bin/NetLogo

            sudo ln -sf \
              "${NETLOGO_HOME}/bin/NetLogo" \
              /usr/local/bin/netlogo
            ;;
          "macOS")
            sudo ln -sf \
              "${NETLOGO_HOME}/Contents/MacOS/" \
              /usr/local/bin/NetLogo

            sudo ln -sf \
              "${NETLOGO_HOME}/Contents/MacOS/" \
              /usr/local/bin/netlogo
            ;;
          "Windows")
            cmd //c mklink "C:\Windows\System32\NetLogo.exe" "${NETLOGO_HOME}\NetLogo.exe"
            cmd //c mklink "C:\Windows\System32\netlogo.exe" "${NETLOGO_HOME}\NetLogo.exe"
            ;;
        esac
      shell: bash

    - name: Test NetLogo installation
      run: |
        # Test NetLogo installation
        netlogo --headless --version
      shell: bash
